### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by MarvinJanssen** [lgalabru/clarity-repl#1]
I would like to use a part of this project in Lumio (https://github.com/MarvinJanssen/lumio/), either as a submodule or some other way, if possible. However, it looks like the license is missing.

**Comment by lgalabru** [comment]
Correct. Since this repo is deriving from https://github.com/blockstack/stacks-blockchain, I think it needs to be GPL-3.0.

**Comment by lgalabru** [comment]
That being said, Lumio could just use the WASM build if the license is an issue.

**Comment by MarvinJanssen** [comment]
I would ideally want to add a build script that places it in /public/build, instead of adding a binary. People can then `npm run build:repl` or something if they want REPL support in Lumio. However, I want to keep the MIT license. I already have a working implementation of the WASM. I could also link to the build on Amazon AWS but I prefer to not link anything external.

**Comment by MarvinJanssen** [comment]
Any updates on this? Should I adopt GPL or include a build script that clones this repository and builds it (but does not include the source code)?

**Comment by lgalabru** [comment]
Hi Marvin! Just updated the repo - https://github.com/lgalabru/clarity-lsp/commit/e4ee843710a6a1d5995d23c69a615708cfd75511
Concerning the next steps for Lumio, I guess either way, both options look viable to me. I think I would probably keep it MIT, host a WASM, and explain / script the wasm build process.

**Comment by MarvinJanssen** [comment]
Thanks, I will consider and cook something up. You can already see an implementation in action on lumio.app. Will update the repository as soon as possible.
